/*
 l * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.awt.Font;
import javax.swing.JMenuItem;
import javax.swing.KeyStroke;
import java.awt.event.KeyEvent;
import java.awt.event.InputEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author ishan
 */
public class StandardCalculator extends javax.swing.JFrame {

    double fNumber ;
    double sNumber ;
    double answer;
    String operation ;
    
    
    
    public StandardCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        basePanel = new javax.swing.JPanel();
        display = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        equation = new javax.swing.JLabel();
        off = new javax.swing.JRadioButton();
        on = new javax.swing.JRadioButton();
        square = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        sqrt = new javax.swing.JButton();
        bacspace = new javax.swing.JButton();
        oneOverX = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        plusORminus = new javax.swing.JButton();
        plus = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        lo = new javax.swing.JButton();
        minus = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        percentage = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        point = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        scientific = new javax.swing.JMenuItem();
        scientific.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		new ScientificCal();

        	}
        });
        units = new javax.swing.JMenuItem();
        units.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		new UnitConverter();
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Standard Calculator");
        setResizable(false);

        basePanel.setBackground(new java.awt.Color(255, 255, 255));

        display.setBackground(new java.awt.Color(0, 0, 0));
        display.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        display.setForeground(new java.awt.Color(255, 255, 255));
        display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        display.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Standard Calculator");
        jLabel1.setIconTextGap(6);

        equation.setBackground(new java.awt.Color(255, 255, 102));
        equation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        equation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        equation.setOpaque(true);

        buttonGroup1.add(off);
        off.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        off.setText("OFF");
        off.setFocusPainted(false);
        off.setFocusable(false);
        off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offActionPerformed(evt);
            }
        });

        buttonGroup1.add(on);
        on.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        on.setText("ON");
        on.setFocusPainted(false);
        on.setFocusable(false);
        on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onActionPerformed(evt);
            }
        });

        square.setBackground(new java.awt.Color(51, 255, 51));
        square.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        square.setText("X^2");
        square.setBorderPainted(false);
        square.setFocusPainted(false);
        square.setFocusable(false);
        square.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(255, 0, 0));
        clear.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("C");
        clear.setBorderPainted(false);
        clear.setFocusPainted(false);
        clear.setFocusable(false);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        sqrt.setBackground(new java.awt.Color(51, 255, 51));
        sqrt.setFont(new Font("Arial Black", Font.BOLD, 16)); // NOI18N
        sqrt.setText("sqrt");
        sqrt.setBorderPainted(false);
        sqrt.setFocusPainted(false);
        sqrt.setFocusable(false);
        sqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtActionPerformed(evt);
            }
        });

        bacspace.setBackground(new java.awt.Color(51, 255, 51));
        bacspace.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        bacspace.setText("<--");
        bacspace.setBorderPainted(false);
        bacspace.setFocusPainted(false);
        bacspace.setFocusable(false);
        bacspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bacspaceActionPerformed(evt);
            }
        });

        oneOverX.setBackground(new java.awt.Color(51, 255, 51));
        oneOverX.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        oneOverX.setText("1/X");
        oneOverX.setBorderPainted(false);
        oneOverX.setFocusPainted(false);
        oneOverX.setFocusable(false);
        oneOverX.setPreferredSize(new java.awt.Dimension(57, 43));
        oneOverX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneOverXActionPerformed(evt);
            }
        });

        seven.setBackground(new java.awt.Color(0, 102, 255));
        seven.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        seven.setText("7");
        seven.setBorderPainted(false);
        seven.setFocusPainted(false);
        seven.setFocusable(false);
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        eight.setBackground(new java.awt.Color(0, 102, 255));
        eight.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        eight.setText("8");
        eight.setBorderPainted(false);
        eight.setFocusPainted(false);
        eight.setFocusable(false);
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        nine.setBackground(new java.awt.Color(0, 102, 255));
        nine.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        nine.setText("9");
        nine.setBorderPainted(false);
        nine.setFocusPainted(false);
        nine.setFocusable(false);
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        plusORminus.setBackground(new java.awt.Color(51, 255, 51));
        plusORminus.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        plusORminus.setText("+/-");
        plusORminus.setBorderPainted(false);
        plusORminus.setFocusPainted(false);
        plusORminus.setFocusable(false);
        plusORminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusORminusActionPerformed(evt);
            }
        });

        plus.setBackground(new java.awt.Color(0, 102, 255));
        plus.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        plus.setText("+");
        plus.setBorderPainted(false);
        plus.setFocusPainted(false);
        plus.setFocusable(false);
        plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusActionPerformed(evt);
            }
        });

        four.setBackground(new java.awt.Color(0, 102, 255));
        four.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        four.setText("4");
        four.setBorderPainted(false);
        four.setFocusPainted(false);
        four.setFocusable(false);
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        five.setBackground(new java.awt.Color(0, 102, 255));
        five.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        five.setText("5");
        five.setBorderPainted(false);
        five.setFocusPainted(false);
        five.setFocusable(false);
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        six.setBackground(new java.awt.Color(0, 102, 255));
        six.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        six.setText("6");
        six.setBorderPainted(false);
        six.setFocusPainted(false);
        six.setFocusable(false);
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        lo.setBackground(new java.awt.Color(51, 255, 51));
        lo.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lo.setText("log");
        lo.setBorderPainted(false);
        lo.setFocusPainted(false);
        lo.setFocusable(false);
        lo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loActionPerformed(evt);
            }
        });

        minus.setBackground(new java.awt.Color(0, 102, 255));
        minus.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        minus.setText("-");
        minus.setBorderPainted(false);
        minus.setFocusPainted(false);
        minus.setFocusable(false);
        minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusActionPerformed(evt);
            }
        });

        one.setBackground(new java.awt.Color(0, 102, 255));
        one.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        one.setText("1");
        one.setBorderPainted(false);
        one.setFocusPainted(false);
        one.setFocusable(false);
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        two.setBackground(new java.awt.Color(0, 102, 255));
        two.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        two.setText("2");
        two.setBorderPainted(false);
        two.setFocusPainted(false);
        two.setFocusable(false);
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        three.setBackground(new java.awt.Color(0, 102, 255));
        three.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        three.setText("3");
        three.setBorderPainted(false);
        three.setFocusPainted(false);
        three.setFocusable(false);
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        percentage.setBackground(new java.awt.Color(51, 255, 51));
        percentage.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        percentage.setText("%");
        percentage.setBorderPainted(false);
        percentage.setFocusPainted(false);
        percentage.setFocusable(false);
        percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentageActionPerformed(evt);
            }
        });

        multiply.setBackground(new java.awt.Color(0, 102, 255));
        multiply.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        multiply.setText("X");
        multiply.setBorderPainted(false);
        multiply.setFocusPainted(false);
        multiply.setFocusable(false);
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });

        point.setBackground(new java.awt.Color(255, 0, 0));
        point.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        point.setForeground(new java.awt.Color(255, 255, 255));
        point.setText(".");
        point.setBorderPainted(false);
        point.setFocusPainted(false);
        point.setFocusable(false);
        point.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointActionPerformed(evt);
            }
        });

        zero.setBackground(new java.awt.Color(0, 102, 255));
        zero.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        zero.setText("0");
        zero.setBorderPainted(false);
        zero.setFocusPainted(false);
        zero.setFocusable(false);
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        equal.setBackground(new java.awt.Color(255, 0, 0));
        equal.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        equal.setForeground(new java.awt.Color(255, 255, 255));
        equal.setText("=");
        equal.setBorderPainted(false);
        equal.setFocusPainted(false);
        equal.setFocusable(false);
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });

        divide.setBackground(new java.awt.Color(0, 102, 255));
        divide.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        divide.setText("/");
        divide.setBorderPainted(false);
        divide.setFocusPainted(false);
        divide.setFocusable(false);
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout basePanelLayout = new javax.swing.GroupLayout(basePanel);
        basePanel.setLayout(basePanelLayout);
        basePanelLayout.setHorizontalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(display)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basePanelLayout.createSequentialGroup()
                        .addComponent(on)
                        .addGap(18, 18, 18)
                        .addComponent(off)
                        .addGap(28, 28, 28)
                        .addComponent(equation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(basePanelLayout.createSequentialGroup()
                        .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(basePanelLayout.createSequentialGroup()
                                .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(square, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(oneOverX, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bacspace, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(basePanelLayout.createSequentialGroup()
                                .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(plusORminus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(basePanelLayout.createSequentialGroup()
                                .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basePanelLayout.createSequentialGroup()
                                .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basePanelLayout.createSequentialGroup()
                                .addComponent(point, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        basePanelLayout.setVerticalGroup(
            basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(equation, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(off)
                        .addComponent(on)))
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(basePanelLayout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addComponent(square, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basePanelLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oneOverX, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sqrt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bacspace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(plusORminus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(percentage, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(point, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(basePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        menuBar.setBackground(new java.awt.Color(255, 255, 255));

        file.setText("File");

        scientific.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        scientific.setText("Scientific Calculator");
        file.add(scientific);

        units.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        units.setText("Unit Conversion");
        file.add(units);

        menuBar.add(file);
        
        mntmNewMenuItem = new JMenuItem("Physical Constant Generator");
        mntmNewMenuItem.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
                new PhysicalConstant();
        		
        	}
        });
        mntmNewMenuItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_B, InputEvent.CTRL_MASK));
        file.add(mntmNewMenuItem);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(basePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offActionPerformed
        zero.setEnabled(false);
        one.setEnabled(false);
        two.setEnabled(false);
        three.setEnabled(false);
        four.setEnabled(false);
        five.setEnabled(false);
        six.setEnabled(false);
        seven.setEnabled(false);
        eight.setEnabled(false);
        nine.setEnabled(false);
        point.setEnabled(false);
        equal.setEnabled(false);
        divide.setEnabled(false);
        clear.setEnabled(false);
        sqrt.setEnabled(false);
        square.setEnabled(false);
        oneOverX.setEnabled(false);
        bacspace.setEnabled(false);
        plusORminus.setEnabled(false);
        lo.setEnabled(false);
        percentage.setEnabled(false);
        plus.setEnabled(false);
        minus.setEnabled(false);
        multiply.setEnabled(false);
        equation.setEnabled(false);
        display.setEnabled(false);
        file.setEnabled(false);
        off.setEnabled(false);
        display.setText("");
        equation.setText("");
        
        
    }//GEN-LAST:event_offActionPerformed

    private void onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onActionPerformed
        
        zero.setEnabled(true);
        one.setEnabled(true);
        two.setEnabled(true);
        three.setEnabled(true);
        four.setEnabled(true);
        five.setEnabled(true);
        six.setEnabled(true);
        seven.setEnabled(true);
        eight.setEnabled(true);
        nine.setEnabled(true);
        point.setEnabled(true);
        equal.setEnabled(true);
        divide.setEnabled(true);
        clear.setEnabled(true);
        sqrt.setEnabled(true);
        square.setEnabled(true);
        oneOverX.setEnabled(true);
        bacspace.setEnabled(true);
        plusORminus.setEnabled(true);
        lo.setEnabled(true);
        percentage.setEnabled(true);
        plus.setEnabled(true);
        minus.setEnabled(true);
        multiply.setEnabled(true);
        equation.setEnabled(true);
        display.setEnabled(true);
        file.setEnabled(true);
        off.setEnabled(true);
        
   
    }//GEN-LAST:event_onActionPerformed

    private void bacspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bacspaceActionPerformed
      
        String bsp = null;
        if(display.getText().length() > 0) {
            
            StringBuilder strb = new StringBuilder(display.getText());
            strb.deleteCharAt(display.getText().length() - 1);
            bsp =strb.toString();
            display.setText(bsp);
        
        }
        
    }//GEN-LAST:event_bacspaceActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        String number1 = display.getText() + one.getText();
        display.setText(number1);
        
    }//GEN-LAST:event_oneActionPerformed

    private void plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusActionPerformed
       try {
           fNumber = Double.parseDouble(String.valueOf(display.getText()));
           display.setText("");
           operation = "+";
       }
       
       catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "Enter a valid number ","just Numbers",JOptionPane.INFORMATION_MESSAGE);
           
       }
       
        
    }//GEN-LAST:event_plusActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        String number0 = display.getText()+ zero.getText();
        display.setText(number0);
    }//GEN-LAST:event_zeroActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        String number2 = display.getText()+ two.getText();
        display.setText(number2);
    }//GEN-LAST:event_twoActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        String number3 = display.getText()+ three.getText();
        display.setText(number3);
    }//GEN-LAST:event_threeActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        String number4 = display.getText()+ four.getText();
        display.setText(number4); 
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
       String number5 = display.getText()+ five.getText();
        display.setText(number5);
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        String number6 = display.getText()+ six.getText();
        display.setText(number6);
    }//GEN-LAST:event_sixActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        String number7 = display.getText()+ seven.getText();
        display.setText(number7);
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        String number8 = display.getText()+ eight.getText();
        display.setText(number8);
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        String number9 = display.getText()+ nine.getText();
        display.setText(number9);
    }//GEN-LAST:event_nineActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        display.setText("");
        equation.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void minusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusActionPerformed
       try {
       
           fNumber = Double.parseDouble(display.getText());
           display.setText("");
           operation = "-";
       
       }       
       catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "Enter a valid number ","just Numbers",JOptionPane.INFORMATION_MESSAGE);
           
       }
        
    }//GEN-LAST:event_minusActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
       
        try {
        
            fNumber = Double.parseDouble(display.getText());
            display.setText("");
            operation = "x";
        }       
       catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "Enter a valid number ","just Numbers",JOptionPane.INFORMATION_MESSAGE);
           
       }
       
    }//GEN-LAST:event_multiplyActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
       
        try {
        
            fNumber = Double.parseDouble(display.getText());
            display.setText("");
            operation = "/";       
        }
   
       catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "Enter a valid number ","just Numbers",JOptionPane.INFORMATION_MESSAGE);
           
       }
        catch(ArithmeticException e){
           JOptionPane.showMessageDialog(null, "Enter a valid number ","Can't divide by zero",JOptionPane.INFORMATION_MESSAGE);
           
       }

    }//GEN-LAST:event_divideActionPerformed

    private void pointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointActionPerformed
        
        if(!display.getText().contains(".")){
        
            display.setText(display.getText() + point.getText());
        
        }        
    }//GEN-LAST:event_pointActionPerformed

    private void plusORminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusORminusActionPerformed
        
        double ops =Double.parseDouble(display.getText());
        ops = ops * (-1);
        display.setText(String.valueOf(ops));      
        
    }//GEN-LAST:event_plusORminusActionPerformed

    private void sqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtActionPerformed
       try {
        double sqroot =Double.parseDouble(String.valueOf(display.getText()));
        double valueOfsqroot =Math.sqrt(sqroot);
        display.setText(String.valueOf(valueOfsqroot));
        equation.setText("Square root of "+sqroot);
       }
       catch(Exception e) {
        
            JOptionPane.showMessageDialog(null, "Enter a number ","just Numbers",JOptionPane.INFORMATION_MESSAGE);        
        }
       
        
  
    }//GEN-LAST:event_sqrtActionPerformed

    private void oneOverXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneOverXActionPerformed
        try {
            String numTF = display.getText();
        double num = 1/Double.parseDouble(numTF);
        String newNum =String.format("%.10f", num);
        display.setText(String.valueOf(newNum));
        equation.setText("1/ " + numTF); 
        }
        catch(Exception e) {
        
            JOptionPane.showMessageDialog(null, "Enter a number ","just Numbers",JOptionPane.INFORMATION_MESSAGE);        
        }
    }//GEN-LAST:event_oneOverXActionPerformed

    private void percentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentageActionPerformed
           fNumber = Double.parseDouble(display.getText());
           display.setText("");
           operation = "%";
    }//GEN-LAST:event_percentageActionPerformed

    private void squareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareActionPerformed
       try {
        double square = Double.parseDouble(display.getText());
        double squaredValue = square * square ;
        display.setText(String.valueOf(squaredValue));
        equation.setText(square +"x"+square);
       
       } 
       catch(Exception e) {
        
            JOptionPane.showMessageDialog(null, "Enter a number ","just Numbers",JOptionPane.INFORMATION_MESSAGE);        
        }
       
        
    }//GEN-LAST:event_squareActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        sNumber =Double.parseDouble(display.getText());
        
        if(operation == "+") {
            
            answer = fNumber + sNumber ;
            display.setText(String.valueOf(answer));
            equation.setText(fNumber +" + " +sNumber);
        }
        else if (operation == "-"){
        
            answer = fNumber - sNumber ;
            display.setText(String.valueOf(answer)); 
            equation.setText(fNumber +" - " +sNumber);
        }
        else if (operation == "x"){
        
            answer = fNumber * sNumber ;
            display.setText(String.valueOf(answer));
            equation.setText(fNumber +" x " +sNumber);
        }
        else if (operation == "/"){
        
            answer = fNumber / sNumber ;
            display.setText(String.valueOf(answer)); 
            equation.setText(fNumber +" / " +sNumber);
        }
        else if (operation == "%"){
        
            answer = fNumber * (sNumber /100) ;
            display.setText(String.valueOf(answer));
            equation.setText(fNumber +" % " +sNumber);           
            
        }
        
        
    }//GEN-LAST:event_equalActionPerformed

    private void loActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loActionPerformed
        double blog =Double.parseDouble(display.getText());
        double log =Math.log10(blog);
        display.setText(String.valueOf(log));
        equation.setText("Log of " + blog);
        
    }//GEN-LAST:event_loActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	
                new StandardCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bacspace;
    private javax.swing.JPanel basePanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JTextField display;
    private javax.swing.JButton divide;
    private javax.swing.JButton eight;
    private javax.swing.JButton equal;
    private javax.swing.JLabel equation;
    private javax.swing.JMenu file;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton minus;
    private javax.swing.JButton multiply;
    private javax.swing.JButton nine;
    private javax.swing.JRadioButton off;
    private javax.swing.JRadioButton on;
    private javax.swing.JButton one;
    private javax.swing.JButton oneOverX;
    private javax.swing.JButton percentage;
    private javax.swing.JButton plus;
    private javax.swing.JButton plusORminus;
    private javax.swing.JButton point;
    private javax.swing.JMenuItem scientific;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton sqrt;
    private javax.swing.JButton square;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JMenuItem units;
    private javax.swing.JButton zero;
    private JMenuItem mntmNewMenuItem;
    // End of variables declaration//GEN-END:variables

}
